### ISSUE TITLE
Load only a part of the robot model instead of whole model

### ISSUE THREAD

**Issue by saikishor** [rbdl/rbdl#79] opened 2023-03-21 16:07 UTC
Hello!

I would like to know with RBDL If it is possible to load only a part of the robot model instead of the whole robot. This is very crucial for the control of the part of the robot where you don't know the information on every joint of the robot at the time of computation. For instance, for a bi-manipulator, it would be interesting

1. Able to choose only one arm to be imported and computed via RBDL and 
2. Able to choose a part of that chain like the last 3 joints of the arm. 

An example robot would be TIAGo++:
![image](https://user-images.githubusercontent.com/10082428/226668836-e235154f-6fd1-474e-a337-07ed44106db5.png)
![image](https://user-images.githubusercontent.com/10082428/226668706-8b4d3fea-d1b6-458c-9eca-4d3b25528c1e.png)

Thank you,

**Comment by ju6ge** [comment] 2023-03-21 20:13
Then just create a new model file only containing the parts you are interested in, by removing all link and joint information that you do not need.

**Comment by saikishor** [comment] 2023-03-21 20:39
Hello @ju6ge,

If I want to have it with the URDF, I believe there is no such functionality in the urdf_parser. If you can confirm it, I can implement myself and open a PR in future. 

Thank you

**Comment by ju6ge** [comment] 2023-03-21 22:24
The URDF file format is just xml the easiest way to accomplish what you want is to just edit that by hand. I mean you could also write a program to do that for you. But that has little to do with the urdf_parser. I mean if you really want to create a tool for that using urdf_parser would be helpful. But there is functionality missing that would first need to be implemented. Meaning you would need to write a model export function.

Then you could write a program that reads a model, then queries the user which parts to keep, then discards the rest and write a new model file only containing remaining parts. But all of that will probably require more time then just editing the model by hand …

**Comment by saikishor** [comment] 2023-03-22 07:54
I see your point @ju6ge. For a quick test, I can edit by hand. However, it is not scalable for future operations. When I get some free time, I can try to implement this feature and open a PR.

Thank you

**Comment by saikishor** [comment] 2023-03-22 08:01
If I implement this or some other new features to the RBDL. Would you be interested to merge them to your `master` @ju6ge ?

**Comment by ju6ge** [comment] 2023-03-22 08:44
RBDL is first and foremost a mathematics library. I don't see a reason to over complicate things by adding structures to select what part of the model is used. If that is required it should be part of a higher level software like [rbdl-toolkit](https://github.com/rbdl/rbdl-toolkit). Also RBDL is not based around URDF per se. URDF model loading is just an addon that parses URDF into the Model Structure used by RBDL for computations. So I really don't see what we are discussing as a feature that RBDL needs, at least not in the core library.

That being said, if you just want to add a utility program for model manipulation it could be integrated into the RBDL codebase how that would look highly depends on how you would want to implement that. And to be clear contributions are welcome.

Here are some key points to consider before you decide to write a new utility/addon:
- Any graphical applications are outside the scope of RBDL itself … that would just introduce more dependencies. If you want that look at the already mentioned `rbdl-toolkit`
- Utilities and Addons that are not part of the core library need to be put behind feature flags, so that you have to opt in to build them.

**Comment by saikishor** [comment] 2023-03-22 08:54
@ju6ge Thank you for the detailed explanation. I wouldn't introduce any GUI as a part of this contribution. They would be simple methods and yes if they belong to utilities they would go inside the addons so they are only built when opted for it. If there are some improvements or new additions as part of RBDL, for instance, CII (Centroidal Inertia Index) computation, that would go inside the core library.

I would add this feature as a part of [construct_model](https://github.com/rbdl/rbdl/blob/master/addons/urdfreader/urdfreader.cc#L62) so it is more generic and wouldn't affect any other things. In the future, we might contribute to the other core things. 

Thank you,

**Comment by ju6ge** [comment] 2023-03-22 08:59
To keep things manageable please make sure to have seperate pull requests for seperate features. That will help with discussion of the suggested changes.

@mjhmilla @martinfelis @pariterre  Any further comments?

**Comment by ju6ge** [comment] 2023-03-22 09:11
Oh and just another thought it would probably be better to have a `construct_part_model` function instead of changing the `construct_model` function, that way only people wishing to load a uncomplete model would need to use it. Otherwise everybody would need to update their function to probably include new parameters.

**Comment by saikishor** [comment] 2023-03-22 09:31
@ju6ge Sure thanks for the insights. Yes, One PR per feature is manageable enough.

Thank you

**Comment by saikishor** [comment] 2023-05-16 22:01
Hello @pariterre @ju6ge,

First of all, I'm extremely sorry for the delay in this part. I've just finished my contributions to some other personal projects and I'm on this part right now, I have some [good progress](https://github.com/saikishor/rbdl/tree/add_construct_partial_model). However, I couldn't find anywhere the code styling guidelines. Could you please point me out the coding styling guidelines that you use, so it would be easy for me to set everything up?

Thank you,

Best Regards,
Sai Kishor Kothakota

**Comment by ju6ge** [comment] 2023-05-16 22:20
Hi @saikishor,

well code style is described in the [CONTRIBUTING.md](https://github.com/rbdl/rbdl/blob/master/CONTRIBUTING.md) 😉

I have used the following command in the past to format PRs 😏
```
astyle -A10 -s2 -xC80 -xL -z2 -xW -xw
```
And by the way no need to apologize, we are all volunteers here.
 
Kind regards,
Felix Richter

**Comment by saikishor** [comment] 2023-05-16 22:24
Hey @ju6ge!

Thanks a lot for the prompt reply. I saw that Contribuing.md documentation, but I was rather expecting some clang formatting file or something similar, but the astyle command you have shared should be fine. 

Thank you,

Best Regards,
Sai Kishor Kothakota

**Comment by ju6ge** [comment] 2023-05-16 22:25
Well there is also an .editorconfig file, so IDEs supporting that could apply the style automatically ;)

**Comment by ju6ge** [comment] 2023-05-16 22:29
Since you are asking about .clang-format. There is still an open pull request with it availible. The problem is that it is based on a version of `rbdl` before the merge with `rbdl-orb`. I have not have had the time to check if the style there is identical to what I used and rebase/cherry-pick the commit(s).

**Comment by saikishor** [comment] 2023-05-16 22:31
> Since you are asking about .clang-format. There is still an open pull request with it availible. The problem is that it is based on a version of `rbdl` before the merge with `rbdl-orb`. I have not have had the time to check if the style there is identical to what I used and rebase/cherry-pick the commit(s).

Awesome. I've just closed my machine, I'll give it a try tomorrow or soon and will update you on it. Thanks

**Comment by ju6ge** [comment] 2023-10-01 11:38
Closed as of #81

**Closed by ju6ge** 2023-10-01 11:38 UTC
