### ISSUE TITLE
Get different result for calculate Jacobian by Python and C++

### ISSUE THREAD

**Issue by jun951113** [rbdl/rbdl#88] opened 2023-09-15 07:03 UTC
Hi Author,

Greeting! I have some problem for calculate Jacobian in C++ and Python. C++: CalcPointJacobian and Python: rbdl.CalcPointJacobian, I get different result for using totally same parameters. Like some of them are zero in Python but other value in C++. Could you please help me solve this problem?

**Comment by ju6ge** [comment] 2023-09-15 11:47
Hi,

I can see that you are new to this. So here are some tips on how to open issues in a way that is helpful and enables a useful response. Because you have given me zero information that could be useful in finding out where the issue is! If I sound annoyed that is because, this happens a lot and it is exhausting having to tell people that if the want help from people who offer their time up for free, they should at the very least also take the time to provide all information that is required to reproduce the issue.

So if you open an issue:
- provide a code snippet: in this case python and c++
- provide all files required for the code to run: in this case model files
- be clear about the versions of the tools you are using! c++ version, cython version and so on … often issues arise from using to old versions!

Kind regards,
ju6ge

**Comment by ju6ge** [comment] 2023-09-15 11:49
Hi,

I can see that you are new to this. So here are some tips on how to open issues in a way that is helpful and enables a useful response. Because you have given me zero information that could be useful in finding out where the issue is! If I sound annoyed that is because, this happens a lot and it is exhausting having to tell people that if the want help from people who offer their time up for free, they should at the very least also take the time to provide all information that is required to reproduce the issue.

So if you open an issue:
- provide a code snippet: in this case python and c++
- provide all files required for the code to run: in this case model files
- be clear about the versions of the tools you are using! c++ version, cython version and so on … often issues arise from using to old versions!

Kind regards,
ju6ge

**Comment by jun951113** [comment] 2023-09-18 12:06
> Hi,
> 
> I can see that you are new to this. So here are some tips on how to open issues in a way that is helpful and enables a useful response. Because you have given me zero information that could be useful in finding out where the issue is! If I sound annoyed that is because, this happens a lot and it is exhausting having to tell people that if the want help from people who offer their time up for free, they should at the very least also take the time to provide all information that is required to reproduce the issue.
> 
> So if you open an issue:
> 
> * provide a code snippet: in this case python and c++
> * provide all files required for the code to run: in this case model files
> * be clear about the versions of the tools you are using! c++ version, cython version and so on … often issues arise from using to old versions!
> 
> Kind regards, ju6ge

Hi,

I am so sorry I provide unclear question last time.
Here is my code and result: for calculate the rbdl.NonlinearEffects:
Here is my python code with result:
![python-q](https://github.com/rbdl/rbdl/assets/40925081/3f685619-db2e-4521-a19c-f77f4f6e9f80)
![python](https://github.com/rbdl/rbdl/assets/40925081/8b23c7eb-b296-47a2-adee-f5c6dab10026)
![python_code](https://github.com/rbdl/rbdl/assets/40925081/50804289-a64b-415a-811e-443c9403e5bc)


and Here is my c++ code with result:
![c++_code](https://github.com/rbdl/rbdl/assets/40925081/e7a034e4-4a17-4209-bd5a-56c79730e4b9)
![c++](https://github.com/rbdl/rbdl/assets/40925081/460965e6-450d-46ef-ab9b-d84fdfdc2356)


Like the photo I provide, I have totally same function: 
rbdl.NonlinearEffects with same q and same q_dot, but I got different result.
Could you please help me with this problem? I am really appreciate about it.
Sorry again for last time I ask really silly question without any details.

**Comment by ju6ge** [comment] 2023-10-01 11:37
Look we are all here doing this in our spare time. If you want help you need to provide your example in way that it is easily reproducible. I do not have the time to try to guess what model you are using what you are computing just to help.

From what you have provided I have no clue what you are trying to accomplish and how you are doing it, there are many parts where something might go wrong. So if you still need help, provide a simple code example in python and in c++ so that i can verify the issue. The code samples should be self contained meaning all information that is required to run it is there. Even better it should be a simple case just enough to show what is going wrong. Otherwise I am closing this issue because it is unclear that the issue is with the library and not how you are using it.

**Closed by ju6ge** 2023-10-01 11:37 UTC
