### ISSUE TITLE
Troubleshooting Installation of RBDL with URDF Reader Addon

### ISSUE THREAD

**Issue by jsuria22** [rbdl/rbdl#100] opened 2024-04-03 22:41 UTC
![1](https://github.com/rbdl/rbdl/assets/124678665/019642de-4c5d-479c-bb58-256e587c3e71)

There appears to be a problem during the execution of the installation script, particularly at the stage where it is compiling and installing rbdl, with a possible issue relating to the urdfreader addon."

My installation from bash

cd rbdl; mkdir -p build; cd build
cmake .. -DRBDL_BUILD_ADDON_URDFREADER=ON -DCMAKE_INSTALL_PREFIX=$1 -DCMAKE_BUILD_TYPE=RELEASE
echo "$(tput setaf 2)==================================="
echo "Compiling and Installing rbdl"
echo "===================================$(tput sgr 0)"
make; make install
cd ../..

How to solve this problem?

**Comment by ju6ge** [comment] 2024-05-04 23:09
Duplicate of #96

**Closed by ju6ge** 2024-05-04 23:09 UTC
